# Generated by Django 3.1.7 on 2021-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_inc_vat', models.DecimalField(decimal_places=2, max_digits=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
